version: "3.5"
services:
    elastic_manager:
        build: docker
        env_file: docker/environment
        volumes:
            - ./src:/elastic_manager/src
            - ./config:/elastic_manager/config
        command: python /elastic_manager/src/elastic_manager.py
