manager:
    thresholds:
        upper: 70 # minimal load to add resource
        lower: 30 # max load to remove resource
    minimal_monitorings: 10 # minimal monitorings to predict load
    lookahead: 10 # steps ahead to predict load
logger:
    level: "DEBUG" #CRITICAL; ERROR; WARNING; INFO; DEBUG; NOTSET
    #filename: manager.log
monitor:
    interval: 2
    host: "192.168.15.249"
    port: 5000
service_config:
    nrf_ip: nrf.free5gc.org
    amf_url: amf{{AMFID}}.free5gc.org # {{AMFID}} will be replaced by id of amf instance
    service_label: 'amf'
    image_name: 'amf'
docker_hosts:
    -
        host: localhost
        port: 2376
        max_services: 1
        network: free5gc-compose_privnet
